import type { Product } from "@/types/product"

// Enhanced mock product data with more products per category
const products: Product[] = [
  // Machine Zone (Electronics) - 6 products
  {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    description: "High-quality wireless headphones with noise cancellation and 30-hour battery life.",
    price: 199.99,
    originalPrice: 249.99,
    discount: 20,
    image: "/wirlesheadphone.jpg",
    category: "Machine Zone",
    categoryId: "machine-zone",
    brand: "AudioTech",
    rating: 4.5,
    reviews: 1234,
    inStock: true,
  },
  {
    id: "2",
    name: "Smart Fitness Watch",
    description: "Track your fitness goals with this advanced smartwatch featuring heart rate monitoring.",
    price: 299.99,
    image: "/fitnessband.jpg",
    category: "Machine Zone",
    categoryId: "machine-zone",
    brand: "FitTech",
    rating: 4.3,
    reviews: 856,
    inStock: true,
  },
  {
    id: "13",
    name: "4K Ultra HD Smart TV",
    description: "55-inch 4K Smart TV with HDR and built-in streaming apps.",
    price: 599.99,
    originalPrice: 799.99,
    discount: 25,
    image: "/smarttv.jpg",
    category: "Machine Zone",
    categoryId: "machine-zone",
    brand: "TechVision",
    rating: 4.6,
    reviews: 432,
    inStock: true,
  },
  {
    id: "14",
    name: "Wireless Charging Pad",
    description: "Fast wireless charging pad compatible with all Qi-enabled devices.",
    price: 39.99,
    image: "/wirelesscharger.jpg",
    category: "Machine Zone",
    categoryId: "machine-zone",
    brand: "ChargeTech",
    rating: 4.4,
    reviews: 267,
    inStock: true,
  },
  {
    id: "15",
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with 360-degree sound and waterproof design.",
    price: 89.99,
    image: "/speaker.jpg",
    category: "Machine Zone",
    categoryId: "machine-zone",
    brand: "SoundWave",
    rating: 4.5,
    reviews: 543,
    inStock: true,
  },
  {
    id: "16",
    name: "Laptop Stand",
    description: "Adjustable aluminum laptop stand for better ergonomics and cooling.",
    price: 49.99,
    image: "/laptopstand.jpg",
    category: "Machine Zone",
    categoryId: "machine-zone",
    brand: "ErgoTech",
    rating: 4.3,
    reviews: 189,
    inStock: true,
  },

  // Fashion Frenzy - 6 products
  {
    id: "3",
    name: "Designer Summer Dress",
    description: "Elegant summer dress perfect for casual and formal occasions.",
    price: 89.99,
    originalPrice: 129.99,
    discount: 30,
    image: "/placeholder.svg?height=400&width=400&text=Summer+Dress",
    category: "Fashion Frenzy",
    categoryId: "fashion-frenzy",
    brand: "StyleCo",
    rating: 4.7,
    reviews: 432,
    inStock: true,
  },
  {
    id: "4",
    name: "Leather Handbag",
    description: "Premium leather handbag with multiple compartments and elegant design.",
    price: 149.99,
    image: "/placeholder.svg?height=400&width=400&text=Leather+Handbag",
    category: "Fashion Frenzy",
    categoryId: "fashion-frenzy",
    brand: "LuxeBags",
    rating: 4.6,
    reviews: 678,
    inStock: true,
  },
  {
    id: "17",
    name: "Casual Sneakers",
    description: "Comfortable casual sneakers perfect for everyday wear.",
    price: 79.99,
    image: "/placeholder.svg?height=400&width=400&text=Sneakers",
    category: "Fashion Frenzy",
    categoryId: "fashion-frenzy",
    brand: "ComfortWalk",
    rating: 4.4,
    reviews: 321,
    inStock: true,
  },
  {
    id: "18",
    name: "Denim Jacket",
    description: "Classic denim jacket with modern fit and premium quality.",
    price: 69.99,
    originalPrice: 89.99,
    discount: 22,
    image: "/placeholder.svg?height=400&width=400&text=Denim+Jacket",
    category: "Fashion Frenzy",
    categoryId: "fashion-frenzy",
    brand: "DenimCo",
    rating: 4.5,
    reviews: 234,
    inStock: true,
  },
  {
    id: "19",
    name: "Silk Scarf",
    description: "Luxurious silk scarf with elegant patterns and vibrant colors.",
    price: 34.99,
    image: "/placeholder.svg?height=400&width=400&text=Silk+Scarf",
    category: "Fashion Frenzy",
    categoryId: "fashion-frenzy",
    brand: "SilkLux",
    rating: 4.7,
    reviews: 156,
    inStock: true,
  },
  {
    id: "20",
    name: "Formal Blazer",
    description: "Professional blazer perfect for business meetings and formal events.",
    price: 129.99,
    image: "/placeholder.svg?height=400&width=400&text=Formal+Blazer",
    category: "Fashion Frenzy",
    categoryId: "fashion-frenzy",
    brand: "BusinessWear",
    rating: 4.6,
    reviews: 287,
    inStock: true,
  },

  // Home Furnishing - 6 products
  {
    id: "5",
    name: "Modern Coffee Table",
    description: "Sleek modern coffee table with glass top and wooden legs.",
    price: 299.99,
    image: "/cofeetable.jpg",
    category: "Home Furnishing",
    categoryId: "home-furnishing",
    brand: "HomeStyle",
    rating: 4.4,
    reviews: 234,
    inStock: true,
  },
  {
    id: "6",
    name: "Ergonomic Office Chair",
    description: "Comfortable office chair with lumbar support and adjustable height.",
    price: 399.99,
    image: "/officechair.jpg",
    category: "Home Furnishing",
    categoryId: "home-furnishing",
    brand: "ComfortSeating",
    rating: 4.5,
    reviews: 567,
    inStock: true,
  },
  {
    id: "21",
    name: "Dining Table Set",
    description: "6-seater dining table set with modern design and durable construction.",
    price: 799.99,
    originalPrice: 999.99,
    discount: 20,
    image: "/dinningtable.jpg",
    category: "Home Furnishing",
    categoryId: "home-furnishing",
    brand: "DiningCo",
    rating: 4.7,
    reviews: 123,
    inStock: true,
  },
  {
    id: "22",
    name: "Floor Lamp",
    description: "Modern floor lamp with adjustable brightness and sleek design.",
    price: 89.99,
    image: "/lamp.jpg",
    category: "Home Furnishing",
    categoryId: "home-furnishing",
    brand: "LightCo",
    rating: 4.3,
    reviews: 198,
    inStock: true,
  },
  {
    id: "23",
    name: "Throw Pillows Set",
    description: "Set of 4 decorative throw pillows with premium fabric covers.",
    price: 49.99,
    image: "/pillow.jpg",
    category: "Home Furnishing",
    categoryId: "home-furnishing",
    brand: "ComfortHome",
    rating: 4.5,
    reviews: 345,
    inStock: true,
  },
  {
    id: "24",
    name: "Wall Art Canvas",
    description: "Beautiful canvas wall art to enhance your living space.",
    price: 79.99,
    image: "/wallart.jpg",
    category: "Home Furnishing",
    categoryId: "home-furnishing",
    brand: "ArtDecor",
    rating: 4.6,
    reviews: 267,
    inStock: true,
  },

  // BookWorms Paradise - 6 products
  {
    id: "7",
    name: "The Art of Programming",
    description: "Comprehensive guide to modern programming techniques and best practices.",
    price: 49.99,
    image: "/artprogramming.jpg",
    category: "BookWorms Paradise",
    categoryId: "bookworms-paradise",
    brand: "TechBooks",
    rating: 4.8,
    reviews: 892,
    inStock: true,
  },
  {
    id: "8",
    name: "Mystery Novel Collection",
    description: "Thrilling collection of mystery novels from bestselling authors.",
    price: 34.99,
    originalPrice: 49.99,
    discount: 30,
    image: "/novel.jpg",
    category: "BookWorms Paradise",
    categoryId: "bookworms-paradise",
    brand: "PageTurner",
    rating: 4.6,
    reviews: 1456,
    inStock: true,
  },
  {
    id: "25",
    name: "Science Fiction Anthology",
    description: "Collection of award-winning science fiction short stories.",
    price: 29.99,
    image: "/sciencefiction.jpg",
    category: "BookWorms Paradise",
    categoryId: "bookworms-paradise",
    brand: "FutureBooks",
    rating: 4.7,
    reviews: 543,
    inStock: true,
  },
  {
    id: "26",
    name: "Cookbook Collection",
    description: "Professional cookbook with 200+ recipes from world cuisines.",
    price: 39.99,
    image: "/recepiebook.jpg",
    category: "BookWorms Paradise",
    categoryId: "bookworms-paradise",
    brand: "CulinaryArts",
    rating: 4.5,
    reviews: 234,
    inStock: true,
  },
  {
    id: "27",
    name: "Self-Help Guide",
    description: "Motivational self-help book for personal development and success.",
    price: 24.99,
    image: "/selfhelp.jpg",
    category: "BookWorms Paradise",
    categoryId: "bookworms-paradise",
    brand: "MotivateMe",
    rating: 4.4,
    reviews: 678,
    inStock: true,
  },
  {
    id: "28",
    name: "History Encyclopedia",
    description: "Comprehensive encyclopedia covering world history and civilizations.",
    price: 59.99,
    originalPrice: 79.99,
    discount: 25,
    image: "/history.jpg",
    category: "BookWorms Paradise",
    categoryId: "bookworms-paradise",
    brand: "HistoryPress",
    rating: 4.8,
    reviews: 321,
    inStock: true,
  },

  // Stationary Sanctuary - 6 products
  {
    id: "9",
    name: "Premium Notebook Set",
    description: "High-quality notebook set with dotted pages, perfect for journaling and note-taking.",
    price: 24.99,
    image: "/placeholder.svg?height=400&width=400&text=Notebook+Set",
    category: "Stationary Sanctuary",
    categoryId: "stationary-sanctuary",
    brand: "WriteWell",
    rating: 4.5,
    reviews: 324,
    inStock: true,
  },
  {
    id: "10",
    name: "Professional Pen Collection",
    description: "Elegant pen collection for professional writing and signing documents.",
    price: 79.99,
    image: "/placeholder.svg?height=400&width=400&text=Pen+Collection",
    category: "Stationary Sanctuary",
    categoryId: "stationary-sanctuary",
    brand: "PenCraft",
    rating: 4.7,
    reviews: 189,
    inStock: true,
  },
  {
    id: "29",
    name: "Desk Organizer",
    description: "Multi-compartment desk organizer to keep your workspace tidy.",
    price: 34.99,
    image: "/placeholder.svg?height=400&width=400&text=Desk+Organizer",
    category: "Stationary Sanctuary",
    categoryId: "stationary-sanctuary",
    brand: "OrganizePro",
    rating: 4.4,
    reviews: 156,
    inStock: true,
  },
  {
    id: "30",
    name: "Highlighter Set",
    description: "Set of 12 vibrant highlighters for studying and office work.",
    price: 19.99,
    image: "/placeholder.svg?height=400&width=400&text=Highlighters",
    category: "Stationary Sanctuary",
    categoryId: "stationary-sanctuary",
    brand: "ColorMark",
    rating: 4.3,
    reviews: 287,
    inStock: true,
  },
  {
    id: "31",
    name: "Sticky Notes Pack",
    description: "Assorted sticky notes pack with different sizes and colors.",
    price: 14.99,
    image: "/placeholder.svg?height=400&width=400&text=Sticky+Notes",
    category: "Stationary Sanctuary",
    categoryId: "stationary-sanctuary",
    brand: "StickyPro",
    rating: 4.2,
    reviews: 432,
    inStock: true,
  },
  {
    id: "32",
    name: "Calculator",
    description: "Scientific calculator with advanced functions for students and professionals.",
    price: 29.99,
    image: "/placeholder.svg?height=400&width=400&text=Calculator",
    category: "Stationary Sanctuary",
    categoryId: "stationary-sanctuary",
    brand: "CalcTech",
    rating: 4.6,
    reviews: 198,
    inStock: true,
  },

  // GameSphere - 6 products
  {
    id: "11",
    name: "Wireless Gaming Controller",
    description: "High-precision gaming controller with customizable buttons and RGB lighting.",
    price: 79.99,
    image: "/placeholder.svg?height=400&width=400&text=Gaming+Controller",
    category: "GameSphere",
    categoryId: "gamesphere",
    brand: "GameTech",
    rating: 4.6,
    reviews: 756,
    inStock: true,
  },
  {
    id: "12",
    name: "Gaming Headset Pro",
    description: "Professional gaming headset with surround sound and noise-canceling microphone.",
    price: 129.99,
    originalPrice: 159.99,
    discount: 19,
    image: "/placeholder.svg?height=400&width=400&text=Gaming+Headset",
    category: "GameSphere",
    categoryId: "gamesphere",
    brand: "AudioGame",
    rating: 4.8,
    reviews: 543,
    inStock: true,
  },
  {
    id: "33",
    name: "Gaming Keyboard",
    description: "Mechanical gaming keyboard with RGB backlighting and programmable keys.",
    price: 99.99,
    image: "/placeholder.svg?height=400&width=400&text=Gaming+Keyboard",
    category: "GameSphere",
    categoryId: "gamesphere",
    brand: "KeyMaster",
    rating: 4.5,
    reviews: 234,
    inStock: true,
  },
  {
    id: "34",
    name: "Gaming Mouse Pad",
    description: "Large gaming mouse pad with smooth surface and anti-slip base.",
    price: 24.99,
    image: "/placeholder.svg?height=400&width=400&text=Mouse+Pad",
    category: "GameSphere",
    categoryId: "gamesphere",
    brand: "PadPro",
    rating: 4.3,
    reviews: 345,
    inStock: true,
  },
  {
    id: "35",
    name: "Gaming Chair",
    description: "Ergonomic gaming chair with lumbar support and adjustable armrests.",
    price: 299.99,
    originalPrice: 399.99,
    discount: 25,
    image: "/placeholder.svg?height=400&width=400&text=Gaming+Chair",
    category: "GameSphere",
    categoryId: "gamesphere",
    brand: "ComfortGame",
    rating: 4.7,
    reviews: 167,
    inStock: true,
  },
  {
    id: "36",
    name: "VR Headset",
    description: "Virtual reality headset for immersive gaming and entertainment.",
    price: 399.99,
    image: "/placeholder.svg?height=400&width=400&text=VR+Headset",
    category: "GameSphere",
    categoryId: "gamesphere",
    brand: "VirtualTech",
    rating: 4.6,
    reviews: 289,
    inStock: true,
  },
]

export async function getProducts(): Promise<Product[]> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 100))
  return products
}

export async function getProductById(id: string): Promise<Product | null> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 100))
  return products.find((product) => product.id === id) || null
}

export async function getProductsByCategory(categoryId: string): Promise<Product[]> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 100))
  return products.filter((product) => product.categoryId === categoryId)
}
